name: CI-CACHED-WINDOWS
on: [workflow_dispatch]

env:
  OPAMYES: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ocaml-compiler: [5.3.0]
        setup-version: [v3]

    outputs:
      total_matrix_jobs: ${{ strategy.job-total || 0 }}
      metric: ${{ steps.collect-metrics.outputs.metric }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Start Build Timer
        uses: ./.github/actions/ci-utils
        with:
          command: start-timer

      - name: Setup Ocaml with v3
        if: matrix.setup-version == 'v3'
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: install Perl deps
        if: runner.os == 'Windows'
        run: |
          set -x
          cpan -j tools/Config.pm -T -f -i String::ShellQuote || true
          cpan -j tools/Config.pm -T -f -i IPC::System::Simple || true
          cpan -J
          perl -MString::Shellquote -e 'print "String::ShellQuote installed\n"'
          perl -MIPC::System::Simple -e 'print "IPC::System::Simple installed\n"'
        shell: bash

      - name: pwd
        run: |
          opam exec -- pwd

      - name: Restore Cached Opam
        id: cache-opam-restore
        uses: actions/cache/restore@v4
        with:
          path: D:\a\camlp5-buildscripts\camlp5-buildscripts\_opam
          key: windows-${{ matrix.ocaml-compiler }}-with-test-${{ matrix.setup-version }}-cache

      - name: Show what is cached
        run: |
          opam switch
          opam list
          opam pin list

      - name: Pin some dependencies
        if: matrix.setup-version == 'v3'
        run: |
          opam pin add --no-action ocamlfind https://github.com/chetmurthy/ocamlfind.git
          opam install . --deps-only --with-doc --with-test

      - name: Install dependencies
        run: |
          opam install --deps-only --with-test .

      - name: Save Opam To Cache
        id: cache-opam-save
        uses: actions/cache/save@v4
        with:
          path: D:\a\camlp5-buildscripts\camlp5-buildscripts\_opam
          key: ${{ steps.cache-opam-restore.outputs.cache-primary-key }}

      - name: List packages
        run: opam list

      - name: build it
        run: |
          opam exec -- make sys
        shell: bash

      - name: test it
        run: |
          opam exec -- make test
        shell: bash

      - name: Do it with opam
        run: opam install -t .

      - name: Collect Build Metrics
        id: collect-metrics
        uses: ./.github/actions/ci-utils
        with:
          command: collect-metrics
          os: ${{ matrix.os }}
          ocaml-version: ${{ matrix.ocaml-compiler }}
          cache-hit: ${{ runner.os != 'Windows' && steps.cache-opam-unix.outputs.cache-hit || steps.cache-opam-windows.outputs.cache-hit }}

  build-results:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Build Summary
        uses: ./.github/actions/ci-utils
        with:
          command: generate-summary
          total-builds: ${{ needs.build.outputs.total_matrix_jobs }}
